### ISSUE TITLE
Usage with Traefik

### ISSUE THREAD

**Issue by sieuwe** [gurucomputing/meshcentral-docker#2]
Do you have a docker-compose for usage with Traefik?
When I use port 80 for binding, I get 'ERR_TOO_MANY_REDIRECTS'.
And with port 443 I get a 'Bad Gateway error'.

When I deploy the container without traefik, I can connect to 443 without any issues.

**Comment by routerino** [comment]
I don't have a traefik example (and won't, there's dozens of reverse proxies these days).

Your problem is most likely that traefik is not expecting a https endpoint. Port 80 won't work because meshcentral redirects to 443. For 443 you'll have to either have the traefik container trust the meshcentral internal certificate, or more likely include `tls insecure skip verify` in your traefik config.
